name: code styling

on: [ pull_request ]

jobs:
  phplint:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run laravel-pint
        uses: aglipanci/laravel-pint-action@2.6
        with:
          preset: laravel

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Fix styling
